lints: rewrite n_san_iana_pub_suffix_empty.
Reworked `n_san_iana_pub_suffix_empty`:

While looking at this lint I noticed it has some weird behaviour:

* It could only flag at most one info result per cert.
* It didn't include the name that tripped the result in the details.
* It would return NA for a whole cert if one name failed to parse but
with a different error than the one used to determine it's a suffix.

I've updated the implementation to address all of the above. It collects
up a list of bad names per-cert, includes them in a details message, and
doesn't return NA for parse errors unrelated to suffixes. The unit tests
were also not table driven so I rewrote those quickly and included
a test case based on my integration test update and a test case with
multiple bare public suffixes.

Updated integration test data:

Here's the story about the expected integration test data change for
`n_san_iana_pub_suffix_empty` with lots of detail on the debugging process.

First to find out what certificate changed from an info result to a pass result
I ran the integration tests with `-fingerprintSummary` for just that one lint
with both the ZCrypto version in this branch and the one on master.

```
make integration INT_FLAGS="-fingerprintSummary -lintFilter='n_san_iana_pub_suffix_empty'"
```

I cut out the fingerprint summary and diff'd the output between versions to spot
the one certificate FP that disappeared with the updated ZCrypto. It was
`d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc`.

Next I ran the `certByFP.sh` script to pull out that cert from the corpus and
get a link to it on Censys.

```
./integration/certByFP.sh d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc
<snipped>
https://censys.io/certificates/d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc
```

Then I ran the lint with the old ZCrypto in dlv and set a breakpoint in the
lint.

```
dlv debug ./cmd/zlint -- -includeNames='n_san_iana_pub_suffix_empty' -pretty ~/Downloads/UnsortedChrome/d570517b96eb7e3db7c6986f421e988fdae8f417295baade0dfc9e6edf8d12cc.pem
break pubsuffix.Execute
```

I stepped through until there was a parse error and printed it:

```
(dlv) p parsedName
github.com/zmap/zcrypto/x509.ParsedDomainName {
	DomainString: "www.theaterpreise.ch\n\n",
	ParsedDomain: *github.com/weppos/publicsuffix-go/publicsuffix.DomainName nil,
	ParseError: error(*errors.errorString) *{
		s: "www.theaterpreise.ch\n\n is a suffix",},}
```

A borked DNS SAN with two trailing newlines was incorrectly deemed a suffix by publicsuffix-go.

Repeating the process with the updated ZCrypto/publicsuffix-go:

```
(dlv) p parsedName
github.com/zmap/zcrypto/x509.ParsedDomainName {
	DomainString: "www.theaterpreise.ch\n\n",
	ParsedDomain: *github.com/weppos/publicsuffix-go/publicsuffix.DomainName {
		TLD: "ch\n\n",
		SLD: "theaterpreise",
		TRD: "www",
		Rule: *(*"github.com/weppos/publicsuffix-go/publicsuffix.Rule")(0xc000108e40),},
	ParseError: error nil,}
```

No more parse error, just a whacky TLD with two newlines. This shouldn't return
an info result for `n_san_iana_pub_suffix_empty` and now with updated deps it
doesn't. TL;DR - old behaviour was a bug we accidentally fixed.