ci: update to Go 1.11.x (#252)
Previously CI was running tests under Go 1.9.x and this is no longer
listed as a stable version. Using Go 1.11.x tests against the newest
stable version available at the time of writing.

In addition to changing the CI version one file (`util/ip.go`) requires a `go
fmt -s` update using the Go 1.11.x toolchain in order for (`TestGoFmt`) to
pass.

Before the update:
```
$ go version
go1.11.5 linux/amd64
$ make test
GORACE=halt_on_error=1 go test -race ./...
--- FAIL: TestGofmt (0.25s)
    gofmt_test.go:37: glob util/*.go not gofmt'ed
    FAIL
    FAIL  github.com/zmap/zlint 0.275s
<snipped>
```

After:
```
$ go version
go1.11.5 linux/amd64
$ make test
ok  	github.com/zmap/zlint	0.191s
<snipped>
```