lints: fix bug in lint_qcstatem_qclimitvalue_valid.go
The `e_qcstatem_qclimitvalue_valid` linter was blinding performing
a type cast that could fail in some real-world conditions. This fix
checks if the type cast fails and returns an error lint result instead
of panicing.

A small test cases is added that lints the real-world certificate that
triggered the bug. Before applying the fix in this branch the test
fails as expected:
```
$ go test -v --test.run TestQcStatemQcLimitValueValid ./lints/...
=== RUN   TestQcStatemQcLimitValueValid
--- FAIL: TestQcStatemQcLimitValueValid (0.00s)
panic: interface conversion: util.EtsiQcStmtIf is util.EtsiQcSscd, not util.EtsiQcLimitValue [recovered]
	panic: interface conversion: util.EtsiQcStmtIf is util.EtsiQcSscd, not util.EtsiQcLimitValue

goroutine 5 [running]:
testing.tRunner.func1(0xc00012a600)
	/usr/lib/go/src/testing/testing.go:830 +0x388
panic(0x7c9040, 0xc0002dea80)
	/usr/lib/go/src/runtime/panic.go:522 +0x1b5
github.com/zmap/zlint/lints.(*qcStatemQcLimitValueValid).Execute(0xc3f450, 0xc000272a80, 0xc0002b0101)
	/home/daniel/go/src/github.com/zmap/zlint/lints/lint_qcstatem_qclimitvalue_valid.go:60 +0x59a
github.com/zmap/zlint/lints.(*Lint).Execute(0xc0002aac00, 0xc000272a80, 0x85b992)
	/home/daniel/go/src/github.com/zmap/zlint/lints/base.go:114 +0x94
github.com/zmap/zlint/lints.TestQcStatemQcLimitValueValid(0xc00012a600)
	/home/daniel/go/src/github.com/zmap/zlint/lints/lint_qcstatem_qclimitvalue_valid_test.go:25 +0x1e8
testing.tRunner(0xc00012a600, 0x878ef0)
	/usr/lib/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:916 +0x357
FAIL	github.com/zmap/zlint/lints	0.008s
```

Afterwards, it passes :tada:

```
$ go test -v --test.run TestQcStatemQcLimitValueValid ./lints/...
=== RUN   TestQcStatemQcLimitValueValid
--- PASS: TestQcStatemQcLimitValueValid (0.00s)
PASS
ok  	github.com/zmap/zlint/lints	0.005s
```